# Use an official Python runtime as a parent image
FROM python:3.11-slim-buster AS fastapi-builder

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file first
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project files
COPY . .

# Expose the port for FastAPI
EXPOSE 1236

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "1236"]