version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    container_name: fastapi_app
    ports:
      - "1236:1236"  # Expose FastAPI on host
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/tasks_db
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app_network
    depends_on:
      - db
      - redis

  telegram_service:
    build:
      context: .
      dockerfile: Dockerfile-telegram
    container_name: telegram_service
    ports:
      - "8001:8001"  # Expose the telegram microservice on port 8001.

     
    networks:
      - app_network
    depends_on:
      - db
      - redis

  react-frontend:
    build: 
      context: ./react-frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://fastapi:1236  # Use localhost for browser access
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - fastapi
      - telegram_service  # Add telegram_service as a dependency
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    networks:
      - app_network
  
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge