version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    container_name: fastapi_app
    ports:
      - "1236:1236"  # Expose FastAPI on host
    environment:
      - GOOGLE_API_KEY=1
      - DATABASE_URL=1
      - REDIS_URL=1
    networks:
      - app_network
    depends_on:
      - db
      - redis

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"  # Expose Streamlit on host
    depends_on:
      - fastapi
    environment:
      - FASTAPI_BASE_URL=http://fastapi:1236
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    networks:
      - app_network
  
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge