# Use an official Python runtime as a parent image
FROM python:3.11-slim-buster AS streamlit-builder

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file first
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install streamlit

# Copy the rest of the project files
COPY . .

# Expose the port for Streamlit
EXPOSE 8501

# Command to run the application
# You'll need to have a streamlit app file, e.g., `streamlit_app.py`
CMD ["streamlit", "run", "streamlit_app.py","--server.address","0.0.0.0","--server.port","8501"]