  # Use an official Python runtime as a parent image
  FROM python:3.11-slim-buster
  
  # Set the working directory in the container
  WORKDIR /app
  
  # Copy the requirements file first
  COPY requirements.txt .
  
  # Install dependencies
  RUN pip install --default-timeout=100 --no-cache-dir -r requirements.txt && pip install sqlalchemy psycopg2-binary redis python-telegram-bot
  
  # Copy the rest of the project files
  COPY . .
  
  # Expose the port for the Telegram service
  EXPOSE 8001
  
  # Command to run the Telegram service
  CMD ["uvicorn", "telegram_service:app", "--host", "0.0.0.0", "--port", "8001"]
